'use client'
import type { Metadata } from 'next'
import Header from '@/components/Header'
import { Inter } from 'next/font/google'
import './globals.css'
import client from '@/lib/github/client'
import { ApolloProvider } from '@apollo/client'

const inter = Inter({ subsets: ['latin'] })

/* export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
} */

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ApolloProvider client={client}>
        {' '}
        <body className={inter.className}>
          <Header />
          <div className="">{children}</div>
        </body>
      </ApolloProvider>
    </html>
  )
}
