# GitHub Action for running bonyuta0204/auto-pull-request.
# triggerd by push to release-stg branch.
# first,checkout using checkout action, then use bonyuta0204/auto-pull-request.

name: Create PR

on:
  push:
    branches:
      - release-stg

jobs:
  auto-pull-request:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: auto-pull-request
        uses: bonyuta0204/auto-pull-request@v1
        with:
          src-branch: release-stg
          target-branch: main
